config/routes.rb
Rails.application.routes.draw do
  root 'products#search'
  get '/search', action: :search, controller: 'products'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/country.rb
class Country < ApplicationRecord
    validates :name, presence: true, uniqueness: true
    has_many :products
end

app/models/product.rb
class Product < ApplicationRecord
    validates :title, :description, :price, presence: true

    # Queries
    scope :contains, ->(substr) {
        where("LOWER(title) LIKE ?", "%#{sanitize_sql_like(substr.downcase)}%")
    }
    scope :from_country, -> (country) {
        selected_country = Country.find_by(name: country)
        if country
            where(country_id: selected_country.id)
        end
    }
    scope :priced, -> (comparison_type, base_price) {
        where("price #{comparison_type} #{base_price}")
    }
    scope :lowest_price, -> {
        order(:price)
    }
    scope :highest_price, -> {
        order(price: :desc)
    }
    scope :newest, -> {
        order(:created_at)
    }
    scope :oldest, -> {
        order(created_at: :desc)
    }

    # Relation
    has_many :tags, through: :producttags
    belongs_to :country
end

app/models/product_tag.rb
class ProductTag < ApplicationRecord
  belongs_to :product
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
    validates :title, presence: true, uniqueness: true
    has_many :products, through: :producttags
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def search
    @products = nil
    @countries = Country.all

    if params[:title]
      session[:title] = params[:title]
    end

    @products = Product.contains(session[:title])
    if !@products
      @products = []
    else
      @products = filter_with_params(@products, params) if params[:filters]
    end
  end

  def filter_with_params(relation, params)
      accepted_values = ["highest_price", "lowest_price", "newest", "oldest"]
      not_accepted_values = ["Country"]

      # Filters with no params
      params[:filters].each do |filter_name, filter_value|
        if (accepted_values.include? filter_value) && !(not_accepted_values.include? filter_value)
            relation = relation.send filter_value.to_sym if relation
        end
      end

      relation = filter_for_base_price(relation, params)
      relation = filter_for_country(relation, params)
  end

  def filter_for_base_price(relation, params)
      # Filtering with price
      if (params[:filters][:base_price]) && (params[:filters][:base_price].size > 0) && ([">", "<", "="].include? params[:filters][:filter_with_base_price])
        if params[:filters][:base_price] && params[:filters][:base_price].size > 0
          relation = relation.priced(params[:filters][:filter_with_base_price], params[:filters][:base_price]) if relation
        end
      end

      relation
  end

  def filter_for_country(relation, params)
    # Filters for country
    if params[:filters][:filter_country] != "Filter for country"
      relation = relation.from_country(params[:filters][:filter_country]) if relation
    end

    relation
  end

  private
  def search_params
    params.require(:search).permit(:title)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Spocket</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_products.html.erb
<% @products.each do |product| %>
  <div class="card mb-3">
    <div class="row no-gutters">
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title"><%= product.title %>, $<%= product.price %></h5>
          <p class="card-text"><%= product.description %></p>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/products/search.html.erb
<div id="search-body">
  <div id="search-header">
    <div id="product-input-holder">
      <%= form_tag(search_path, method: :get) do %>
        <%= text_field_tag(:title, params[:title], class: "form-control") %>
      <% end %>
    </div>
  </div>

  <div id="content">
    <% if @products.size > 0 %>
      <div class="card mb-3" id="filter-card">
        <div class="row no-gutters">
          <div class="col-md-8">
            <div class="card-body">
              <%= form_tag(search_path, method: :get) do %>
                <select name="filters[filter_price]" id="filter" style="margin-top: 1em;">
                  <option selected="selected">Price</option>
                  <option value="highest_price">Highest Price</option>
                  <option value="lowest_price">Lowest Price</option>
                </select>

                <select name="filters[filter_new]" id="filter" style="margin-top: 1em;">
                  <option selected="selected">Date</option>
                  <option value="newest">Newest</option>
                  <option value="oldest">Oldest</option>
                </select>

                <select name="filters[filter_with_base_price]" id="filter" style="margin-top: 1em; margin-bottom: 0.5em;">
                  <option selected="selected">Filter with base price</option>
                  <option value="<">Less than</option>
                  <option value="=">Equal</option>
                  <option value=">">Greater than</option>
                </select>
                <%= number_field_tag('filters[base_price]', params[:price_base], placeholder: 'Base price', class: "form-control") %>

                <select name="filters[filter_country]" id="filter" style="margin-top: 1em; margin-bottom: 0.5em;">
                  <option selected="selected">Filter for country</option>
                  <% @countries.each do |country| %>
                    <option value="<%= country.name %>"><%= country.name %></option>
                  <% end %>
                </select>

                <%= submit_tag 'Filter' %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>

    <div id="results-body">
      <% if @products && @products.size > 0 %>
          <%= render partial: 'products' %>
      <% else %>
        <% if @products %>
          <div class="alert alert-warning" role="alert">
              Could not find products!
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

</div>